services:
  # 1. Web Service para el Backend (Node.js)
  - type: web
    name: consultorio-backend
    env: node
    plan: free 
    region: ohio
    rootDir: server
    buildCommand: npm install
    startCommand: npm run db:init && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: DATABASE_URL
        sync: false 
      - key: GOOGLE_AUTH_REDIRECT_URI
        value: https://consultorio-backend-r2su.onrender.com/api/auth/google/callback
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: FRONTEND_URL
        value: https://consultorio-frontend.onrender.com 
      - key: CORS_ORIGIN
        value: https://consultorio-frontend.onrender.com 
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false

  # 2. Static Site para el Frontend (React)
  - type: static
    name: consultorio-frontend
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: build
    # REGLA DE RUTAS: Para evitar el 404 en React al refrescar o redirigir
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://consultorio-backend-r2su.onrender.com
      - key: CI
        value: false
